name: Publish
on:
  push:
    branches:
      - fork-master

env:
  RELEASE_VERSION: "0.4.22"
  DEVELOP_VERSION: "0.4.23-SNAPSHOT"
  GIT_AUTHOR_NAME: "@swisspost-devs"
  GIT_AUTHOR_EMAIL: "oss@post.ch"
  GIT_COMMITTER_NAME: "swisspost-devs"
  GIT_COMMITTER_EMAIL: "oss@post.ch"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: joschi/setup-jdk@v2
      with:
        java-version: '8'
        server-id: sonatype-nexus-staging # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: CI_DEPLOY_USERNAME # env variable for username in deploy
        server-password: CI_DEPLOY_PASSWORD # env variable for token in deploy
        gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: CI_GPG_PASSPHRASE # env variable for GPG private key passphrase
    
    - name: Release
      run: |
        echo "Preparing release ${RELEASE_VERSION}..."
        git fetch
        git reset --hard
        mvn -B release:prepare -Pdo-release -DreleaseVersion=${RELEASE_VERSION} -DdevelopmentVersion=${DEVELOP_VERSION}
        mvn release:perform -Pdo-release
      env:
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        CI_GPG_PASSPHRASE: ${{ secrets.CI_GPG_PASSPHRASE }}
