name: Publish
on:
  push:
    branches:
      - master

env:
  RELEASE_VERSION: "0.4.21"
  DEVELOP_VERSION: "0.4.22-SNAPSHOT"
  GIT_AUTHOR_NAME: "@swisspost-devs"
  GIT_AUTHOR_EMAIL: "oss@post.ch"
  GIT_COMMITTER_NAME: "swisspost-devs"
  GIT_COMMITTER_EMAIL: "oss@post.ch"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: joschi/setup-jdk@v2
      with:
        java-version: '8'
    
    - name: Release
      if: ${{ !contains(github.event.head_commit.message, '[maven-release-plugin]') }}
      run: |
        echo "Preparing release ${RELEASE_VERSION}..."
        mvn --settings settings.xml -B release:prepare -Pdo-release -DreleaseVersion=${RELEASE_VERSION} -DdevelopmentVersion=${DEVELOP_VERSION}
        mvn --settings settings.xml release:perform -Pdo-release